config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :cities

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
require 'rest-client'

class City

  def self.all(api_key)
    response = RestClient.post('http://testapi.novaposhta.ua/v2.0/json/Address/getCities', [{"modelName": "Address",
                                                                                             "calledMethod": "getCities",
                                                                                             "apiKey": api_key
                                                                                             }].to_json)
    JSON.parse(response)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController


  def index
    @api_key = params[:api_key]
    if @api_key.blank?
      flash[:error] = "Please enter your api key"
      redirect_to root_path
    else
      @cities = City.all(@api_key)
      unless @cities[0]["success"]
        flash[:error] = "Wrong api key"
        redirect_to root_path
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/index.html.erb
<h1 class="text-center">Cities where Nova Poshta work</h1>
<table class="table table-striped">
  <tr>
    <th>City id</th>
    <th>City name ru</th>
    <th>City name</th>
  </tr>
    <% @cities[0]["data"].each do |city| %>
  <tr>
    <td><%=  city["CityID"] %></td>
    <td><%=  city["DescriptionRu"] %></td>
    <td><%=  city["Description"] %></td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovaPoshtaCities</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

          <%= yield %>
          <%= bootstrap_flash %>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="text-center">

<h2>Enter Nova Poshta api key</h2>

<%= form_tag cities_path, method: 'get', class: "navbar-form " do %>
<%= submit_tag "Submit", class: "btn btn-default" %>
   <div class="form-group">
     <%= text_field_tag :api_key %>
   </div>
<% end %>
</div>